# controllers:
#     resource:
        # path: ../src/Controller/
        # namespace: App\Controller
    # type: attribute

# new way of routing
hello:
    path: /hello
    controller: App\Controller\HelloController::hello
